### ISSUE TITLE
Question: Problem with PythonOpenSSL

### ISSUE THREAD

**Issue by ghost** [jaywink/diaspora-tools#3]
Hi, when I try to install all requirements, I receive this:

"x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c OpenSSL/crypto/crypto.c -o build/temp.linux-x86_64-2.7/OpenSSL/crypto/crypto.o

OpenSSL/crypto/crypto.c:14:20: fatal error: Python.h: No existe el archivo o el directorio

 #include <Python.h>

```
                ^
```

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1"

What is the problem? Thanks for your work :)

**Comment by jaywink** [comment]
Try installing the Python dev libraries, ie on Debian/Ubuntu it's `python-dev` package?

Please note that this tool is broken on any pod runnng 0.5.x version of diaspora, as said in the readme :(

**Comment by ghost** [comment]
I didn't see the note around the pod version :( Now is useless for my purposes. Many thanks.

**Comment by jaywink** [comment]
Sorry :( The diaspy library probably will not be fixed since the API is so near for diaspora, then it will most likely be quite quickly adapted to use a proper API instead of the JSON endpoints that it currently uses and make it unstable.

I'll update this library once diaspy is in working order again.
